spring:
  application:
    name: ProductCatalog

  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/catalog_feedback_db}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
    properties:
      hibernate:
        format_sql: true

  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.xml

  mail:
    host: ${MAIL_HOST:smtp.gmail.com}
    port: ${MAIL_PORT:587}
    username: ${MAIL_USERNAME:}
    password: ${MAIL_PASSWORD:}

    properties:
      mail:
        smtp:
          auth: ${MAIL_SMTP_AUTH:true}
          starttls:
            enable: ${MAIL_SMTP_STARTTLS:true}
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000

server:
  port: 8080

app:
  feedback:
    admin-email: ${ADMIN_EMAIL:}