spring:
  application:
    name: ProductCatalog

  datasource:
    url: jdbc:postgresql://localhost:5432/catalog_feedback_db
    username: postgres
    password: GjlYjvth999
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
    properties:
      hibernate:
        format_sql: true

  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.xml

  mail:
    host: localhost
    port: 1025
    username:
    password:
    properties:
      mail:
        smtp:
          auth: false
          starttls:
            enable: false

server:
  port: 8080

app:
  feedback:
    admin-email: admin@example.com
